version: "3"
services:
  mysql:
    image: "mysql:8"
    environment:
      MYSQL_ROOT_PASSWORD: "root"
    expose:
      - 3306
    ports:
      - "3306:3306"
  oracle:
    image: store/oracle/database-enterprise:12.2.0.1
    ports:
      - 1521:1521
      - 8080:8080
      - 5500:5500